### ISSUE TITLE
Error: Cannot find module './Controllers/user'

### ISSUE THREAD

**Issue by yech1990** [wchaowu/nodejs#7]
```javascript
module.js:327
    throw err;
    ^

Error: Cannot find module './Controllers/user'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.exports.setRequestUrl (/xxxx/Coding/nodejs/nodejs/NodeSample/routes.js:3:16)
    at Object.<anonymous> (/xxxx/nodejs/nodejs/NodeSample/app.js:27:11)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

```

The 'controllers' folder start with a lowercase letter 'c', but the importing command starts with capital letter 'C'.

**Comment by yech1990** [comment]
```javascript
if(!path.existsSync(root)){
         ^

TypeError: path.existsSync is not a function

```

**Comment by licongmu** [comment]
yeah,the project is created early,it is not suitable in current Node and Express,i'm gonna modify it.

**Comment by yech1990** [comment]
looking forword

**Comment by coderefractor** [comment]
Looking forward

**Comment by rahulg30** [comment]
I am having same issue....also looking forward for the same

**Comment by Firdousrida** [comment]
check the names of the file and folders. spelling mistakes bring error too
